# Generated by Django 6.0.3 on 2026-08-23 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (Turkmen)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)')),
                ('file', models.FileField(upload_to='documents/')),
                ('category', models.CharField(choices=[('Kitaphana', 'Kitaphana (Library)'), ('Sanly Bilim', 'Sanly Bilim (Digital Education)'), ('Hasabat', 'Hepdelik Hasabat (Weekly Report)'), ('Maksatnama', 'Maksatnamalar (Programs)')], default='Hasabat', max_length=50, verbose_name='Category')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Name (Turkmen)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name (English)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Name (Russian)')),
                ('description_tm', models.TextField(verbose_name='Description (Turkmen)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('dean_name_tm', models.CharField(blank=True, max_length=255, verbose_name='Dean Name (Turkmen)')),
                ('dean_name_en', models.CharField(blank=True, max_length=255, verbose_name='Dean Name (English)')),
                ('dean_name_ru', models.CharField(blank=True, max_length=255, verbose_name='Dean Name (Russian)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculties/')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (Turkmen)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)')),
                ('content_tm', models.TextField(verbose_name='Content (Turkmen)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Content (Russian)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views Count')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News List',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (Turkmen)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)')),
                ('year', models.IntegerField(default=2026, verbose_name='Year')),
                ('description_tm', models.TextField(blank=True, verbose_name='Description (Turkmen)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('results_pdf', models.FileField(blank=True, null=True, upload_to='olympiads/results/', verbose_name='Results PDF')),
            ],
            options={
                'verbose_name': 'Olympiad',
                'verbose_name_plural': 'Olympiads',
                'ordering': ['-year', 'title_tm'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Name (Turkmen)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name (English)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Name (Russian)')),
                ('logo', models.ImageField(upload_to='partners/')),
                ('country_tm', models.CharField(blank=True, max_length=255, verbose_name='Country (Turkmen)')),
                ('country_en', models.CharField(blank=True, max_length=255, verbose_name='Country (English)')),
                ('country_ru', models.CharField(blank=True, max_length=255, verbose_name='Country (Russian)')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (Turkmen)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)')),
                ('subtitle_tm', models.CharField(blank=True, max_length=255, verbose_name='Subtitle (Turkmen)')),
                ('subtitle_en', models.CharField(blank=True, max_length=255, verbose_name='Subtitle (English)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, verbose_name='Subtitle (Russian)')),
                ('link', models.URLField(blank=True, verbose_name='Link URL')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Name (Turkmen)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name (English)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Name (Russian)')),
                ('description_tm', models.TextField(verbose_name='Description (Turkmen)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('head_name_tm', models.CharField(blank=True, max_length=255, verbose_name='Head Name (Turkmen)')),
                ('head_name_en', models.CharField(blank=True, max_length=255, verbose_name='Head Name (English)')),
                ('head_name_ru', models.CharField(blank=True, max_length=255, verbose_name='Head Name (Russian)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='website.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
