# Generated by Django 6.0.3 on 2026-08-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (Turkmen)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Title (Russian)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content_tm', models.TextField(blank=True, verbose_name='Content (Turkmen)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Content (Russian)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subpages', to='website.page', verbose_name='Parent Page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'title_tm'],
            },
        ),
    ]
